"""
automation_registry.py

Phase A (config-first) Automation Registry for CA Assist.

The registry defines which automation and assigned agent apply to each task type.
This is in-code configuration for now; no database tables are introduced.
"""

from collections import Counter


CATEGORIES = [
    "GST",
    "TDS",
    "Income Tax",
    "ROC / MCA",
    "Payroll",
    "Audit",
    "Documents",
    "Client Communication",
    "Risk Review",
    "Compliance Calendar",
    "Reconciliation",
    "Credential & Access",
    "Portal RPA",
    "Company Incorporation",
    "Registrations",
    "Evidence Management",
    "Accounting Connectors",
    "External Audit Integration",
]

ASSIGNED_AGENTS = [
    "GST Agent",
    "TDS & Payroll Agent",
    "Income Tax Agent",
    "ROC & MCA Agent",
    "Audit Agent",
    "Document Checklist Agent",
    "Client Communication Agent",
    "Review & Risk Agent",
    "Compliance Calendar Agent",
    "Reconciliation Agent",
    "Credential & Access Agent",
    "GST Portal RPA Agent",
    "Income Tax Portal RPA Agent",
    "MCA Portal RPA Agent",
    "TRACES RPA Agent",
    "PF/ESI Portal RPA Agent",
    "Filing Evidence Agent",
    "Portal Status Monitor Agent",
    "Error Resolution Agent",
    "Company Incorporation Agent",
    "LLP Incorporation Agent",
    "GST Registration Agent",
    "MSME / Udyam Agent",
    "Startup India Agent",
    "Shops & Establishment Agent",
    "Labour Registration Agent",
    "FEMA / FDI Agent",
    "Business License Agent",
    "Accounting Sync Agent",
    "External Stat Audit Agent",
]


AUTOMATION_REGISTRY = [
    # GST
    {
        "key": "gstr1_checklist",
        "name": "GSTR-1 Checklist",
        "description": "Build filing checklist and pre-validation prompts for GSTR-1.",
        "category": "GST",
        "assigned_agent": "GST Agent",
        "task_types": ["gstr1"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "gstr3b_checklist",
        "name": "GSTR-3B Checklist",
        "description": "Create compliance checklist for GSTR-3B preparation.",
        "category": "GST",
        "assigned_agent": "GST Agent",
        "task_types": ["gstr3b"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "gstr3b_draft_working",
        "name": "GSTR-3B Draft Working",
        "description": "Prepare structured draft working notes for GSTR-3B.",
        "category": "GST",
        "assigned_agent": "GST Agent",
        "task_types": ["gstr3b"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "draft_working",
    },
    {
        "key": "gst_itc_reconciliation",
        "name": "GST ITC Reconciliation",
        "description": "Assist with ITC mismatch review and reconciliation notes.",
        "category": "GST",
        "assigned_agent": "GST Agent",
        "task_types": ["gstr3b", "gstr9"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "reconciliation_note",
    },
    {
        "key": "gstr9_annual_checklist",
        "name": "GSTR-9 Annual Checklist",
        "description": "Annual GST return checklist and risk prompts.",
        "category": "GST",
        "assigned_agent": "GST Agent",
        "task_types": ["gstr9"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },

    # TDS
    {
        "key": "tds_section_classification",
        "name": "TDS Section Classification",
        "description": "Classify likely TDS sections and exception prompts.",
        "category": "TDS",
        "assigned_agent": "TDS & Payroll Agent",
        "task_types": ["tds_return", "tds_cert"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "classification_note",
    },
    {
        "key": "tds_24q_checklist",
        "name": "TDS 24Q Checklist",
        "description": "Generate quarterly 24Q preparation checklist.",
        "category": "TDS",
        "assigned_agent": "TDS & Payroll Agent",
        "task_types": ["tds_return"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "tds_26q_checklist",
        "name": "TDS 26Q Checklist",
        "description": "Generate quarterly 26Q preparation checklist.",
        "category": "TDS",
        "assigned_agent": "TDS & Payroll Agent",
        "task_types": ["tds_return"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "form_16_16a_checklist",
        "name": "Form 16/16A Checklist",
        "description": "Checklist for TDS certificate completeness and release.",
        "category": "TDS",
        "assigned_agent": "TDS & Payroll Agent",
        "task_types": ["tds_cert"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },

    # Income Tax
    {
        "key": "itr_document_checklist",
        "name": "ITR Document Checklist",
        "description": "Create ITR document requirement checklist by profile.",
        "category": "Income Tax",
        "assigned_agent": "Income Tax Agent",
        "task_types": ["itr"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "ais_26as_review",
        "name": "AIS/26AS Review",
        "description": "Highlight mismatches between reported and expected tax data.",
        "category": "Income Tax",
        "assigned_agent": "Income Tax Agent",
        "task_types": ["itr"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "risk_report",
    },
    {
        "key": "advance_tax_estimate_note",
        "name": "Advance Tax Estimate Note",
        "description": "Prepare advance-tax estimation working note.",
        "category": "Income Tax",
        "assigned_agent": "Income Tax Agent",
        "task_types": ["advance_tax"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "draft_working",
    },
    {
        "key": "itr_draft_working",
        "name": "ITR Draft Working",
        "description": "Generate structured ITR draft working and assumptions.",
        "category": "Income Tax",
        "assigned_agent": "Income Tax Agent",
        "task_types": ["itr"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "draft_working",
    },

    # ROC / MCA
    {
        "key": "aoc4_checklist",
        "name": "AOC-4 Checklist",
        "description": "Checklist for AOC-4 filing package readiness.",
        "category": "ROC / MCA",
        "assigned_agent": "ROC & MCA Agent",
        "task_types": ["aoc4"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "mgt7_checklist",
        "name": "MGT-7 Checklist",
        "description": "Checklist for annual return preparation and validation.",
        "category": "ROC / MCA",
        "assigned_agent": "ROC & MCA Agent",
        "task_types": ["mgt7"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "dir3kyc_reminder",
        "name": "DIR-3 KYC Reminder",
        "description": "Generate reminder prompts for DIR-3 KYC pending items.",
        "category": "ROC / MCA",
        "assigned_agent": "ROC & MCA Agent",
        "task_types": ["dir3kyc"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "medium",
        "requires_human_review": False,
        "is_active": True,
        "output_type": "message_draft",
    },
    {
        "key": "roc_attachment_checklist",
        "name": "ROC Attachment Checklist",
        "description": "Validate likely supporting attachments for ROC filings.",
        "category": "ROC / MCA",
        "assigned_agent": "ROC & MCA Agent",
        "task_types": ["aoc4", "mgt7"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },

    # Payroll
    {
        "key": "pf_esi_checklist",
        "name": "PF/ESI Checklist",
        "description": "Monthly PF/ESI compliance checklist generation.",
        "category": "Payroll",
        "assigned_agent": "TDS & Payroll Agent",
        "task_types": ["pf_esi"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "professional_tax_checklist",
        "name": "Professional Tax Checklist",
        "description": "Checklist for PT periodic compliance tasks.",
        "category": "Payroll",
        "assigned_agent": "TDS & Payroll Agent",
        "task_types": ["pf_esi"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },

    # Audit (lightweight CA Assist support only)
    {
        "key": "audit_document_request_checklist",
        "name": "Audit Document Request Checklist",
        "description": "Build audit document request checklist from task context and pending evidence.",
        "category": "Audit",
        "assigned_agent": "Document Checklist Agent",
        "task_types": ["tax_audit", "general_query"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "audit_client_email_draft",
        "name": "Audit Client Email Draft",
        "description": "Draft client communication for audit evidence requests and follow-ups.",
        "category": "Audit",
        "assigned_agent": "Client Communication Agent",
        "task_types": ["tax_audit", "general_query"],
        "trigger_type": "on_sync_review",
        "risk_level": "low",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "message_draft",
    },
    {
        "key": "audit_evidence_status_check",
        "name": "Audit Evidence Status Check",
        "description": "Summarize evidence completeness and pending audit support items.",
        "category": "Audit",
        "assigned_agent": "Document Checklist Agent",
        "task_types": ["tax_audit", "general_query"],
        "trigger_type": "on_sync_review",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "risk_report",
    },
    {
        "key": "audit_review_risk_note",
        "name": "Audit Review Risk Note",
        "description": "Prepare reviewer-facing risk note for audit workflow progress and exceptions.",
        "category": "Audit",
        "assigned_agent": "Review & Risk Agent",
        "task_types": ["tax_audit", "general_query"],
        "trigger_type": "on_sync_review",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "risk_report",
    },

    # External Statutory Audit Integration (placeholder registry only)
    {
        "key": "stat_audit_full_workflow",
        "name": "Stat Audit Full Workflow",
        "description": "Placeholder routing for full statutory audit workflow to existing external Stat Audit Agent.",
        "category": "External Audit Integration",
        "assigned_agent": "External Stat Audit Agent",
        "task_types": ["tax_audit", "general_query"],
        "trigger_type": "external_agent_integration",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": False,
        "output_type": "external_stat_audit_result",
    },
    {
        "key": "stat_audit_materiality",
        "name": "Stat Audit Materiality",
        "description": "Placeholder routing for statutory audit materiality analysis to external Stat Audit Agent.",
        "category": "External Audit Integration",
        "assigned_agent": "External Stat Audit Agent",
        "task_types": ["tax_audit"],
        "trigger_type": "external_agent_integration",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": False,
        "output_type": "external_stat_audit_result",
    },
    {
        "key": "stat_audit_sampling",
        "name": "Stat Audit Sampling",
        "description": "Placeholder routing for statutory audit sampling to external Stat Audit Agent.",
        "category": "External Audit Integration",
        "assigned_agent": "External Stat Audit Agent",
        "task_types": ["tax_audit"],
        "trigger_type": "external_agent_integration",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": False,
        "output_type": "external_stat_audit_result",
    },
    {
        "key": "stat_audit_workpaper_review",
        "name": "Stat Audit Workpaper Review",
        "description": "Placeholder routing for statutory workpaper review to external Stat Audit Agent.",
        "category": "External Audit Integration",
        "assigned_agent": "External Stat Audit Agent",
        "task_types": ["tax_audit", "general_query"],
        "trigger_type": "external_agent_integration",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": False,
        "output_type": "external_stat_audit_result",
    },
    {
        "key": "stat_audit_caro_checklist",
        "name": "Stat Audit CARO Checklist",
        "description": "Placeholder routing for CARO checklist generation/review to external Stat Audit Agent.",
        "category": "External Audit Integration",
        "assigned_agent": "External Stat Audit Agent",
        "task_types": ["tax_audit"],
        "trigger_type": "external_agent_integration",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": False,
        "output_type": "external_stat_audit_result",
    },
    {
        "key": "stat_audit_schedule_iii_checklist",
        "name": "Stat Audit Schedule III Checklist",
        "description": "Placeholder routing for Schedule III checklist review to external Stat Audit Agent.",
        "category": "External Audit Integration",
        "assigned_agent": "External Stat Audit Agent",
        "task_types": ["tax_audit"],
        "trigger_type": "external_agent_integration",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": False,
        "output_type": "external_stat_audit_result",
    },
    {
        "key": "stat_audit_observation_review",
        "name": "Stat Audit Observation Review",
        "description": "Placeholder routing for statutory audit observations to external Stat Audit Agent.",
        "category": "External Audit Integration",
        "assigned_agent": "External Stat Audit Agent",
        "task_types": ["tax_audit", "general_query"],
        "trigger_type": "external_agent_integration",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": False,
        "output_type": "external_stat_audit_result",
    },
    {
        "key": "stat_audit_trial_balance_review",
        "name": "Stat Audit Trial Balance Review",
        "description": "Placeholder routing for statutory trial balance review to external Stat Audit Agent.",
        "category": "External Audit Integration",
        "assigned_agent": "External Stat Audit Agent",
        "task_types": ["tax_audit"],
        "trigger_type": "external_agent_integration",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": False,
        "output_type": "external_stat_audit_result",
    },
    {
        "key": "stat_audit_financial_statement_review",
        "name": "Stat Audit Financial Statement Review",
        "description": "Placeholder routing for financial statement review to external Stat Audit Agent.",
        "category": "External Audit Integration",
        "assigned_agent": "External Stat Audit Agent",
        "task_types": ["tax_audit"],
        "trigger_type": "external_agent_integration",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": False,
        "output_type": "external_stat_audit_result",
    },

    # Documents
    {
        "key": "client_document_request_builder",
        "name": "Client Document Request Builder",
        "description": "Build client-friendly document request sets from task context.",
        "category": "Documents",
        "assigned_agent": "Document Checklist Agent",
        "task_types": ["gstr1", "gstr3b", "gstr9", "tds_return", "itr", "aoc4", "mgt7", "pf_esi"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "low",
        "requires_human_review": False,
        "is_active": True,
        "output_type": "document_request_list",
    },
    {
        "key": "missing_document_detector",
        "name": "Missing Document Detector",
        "description": "Detect likely missing documents from task state and comments.",
        "category": "Documents",
        "assigned_agent": "Document Checklist Agent",
        "task_types": ["gstr1", "gstr3b", "gstr9", "tds_return", "itr", "aoc4", "mgt7", "pf_esi"],
        "trigger_type": "on_sync_review",
        "risk_level": "medium",
        "requires_human_review": False,
        "is_active": True,
        "output_type": "risk_report",
    },

    # Client Communication
    {
        "key": "client_email_draft",
        "name": "Client Email Draft",
        "description": "Generate client-ready email draft for task updates.",
        "category": "Client Communication",
        "assigned_agent": "Client Communication Agent",
        "task_types": ["query", "gstr1", "gstr3b", "itr", "tds_return"],
        "trigger_type": "on_sync_review",
        "risk_level": "low",
        "requires_human_review": False,
        "is_active": True,
        "output_type": "message_draft",
    },
    {
        "key": "client_reminder_message",
        "name": "Client Reminder Message",
        "description": "Draft reminder messages for pending documents or approvals.",
        "category": "Client Communication",
        "assigned_agent": "Client Communication Agent",
        "task_types": ["gstr1", "gstr3b", "itr", "aoc4", "mgt7", "pf_esi"],
        "trigger_type": "scheduled",
        "risk_level": "low",
        "requires_human_review": False,
        "is_active": True,
        "output_type": "message_draft",
    },
    {
        "key": "filing_completion_message",
        "name": "Filing Completion Message",
        "description": "Draft filing completion message and next-action summary.",
        "category": "Client Communication",
        "assigned_agent": "Client Communication Agent",
        "task_types": ["gstr1", "gstr3b", "gstr9", "itr", "tds_return", "aoc4", "mgt7"],
        "trigger_type": "on_sync_review",
        "risk_level": "low",
        "requires_human_review": False,
        "is_active": True,
        "output_type": "message_draft",
    },

    # Risk Review
    {
        "key": "ai_output_risk_review",
        "name": "AI Output Risk Review",
        "description": "Assess AI output for risk markers and escalations.",
        "category": "Risk Review",
        "assigned_agent": "Review & Risk Agent",
        "task_types": ["gstr1", "gstr3b", "gstr9", "tds_return", "itr", "aoc4", "mgt7", "pf_esi", "query"],
        "trigger_type": "on_sync_review",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "risk_report",
    },
    {
        "key": "high_risk_escalation",
        "name": "High Risk Escalation",
        "description": "Recommend manager escalation for high-risk outputs.",
        "category": "Risk Review",
        "assigned_agent": "Review & Risk Agent",
        "task_types": ["gstr3b", "gstr9", "itr", "aoc4", "mgt7", "query"],
        "trigger_type": "on_sync_review",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "escalation_note",
    },
    {
        "key": "filing_readiness_check",
        "name": "Filing Readiness Check",
        "description": "Check whether task is filing-ready based on current signals.",
        "category": "Risk Review",
        "assigned_agent": "Review & Risk Agent",
        "task_types": ["gstr1", "gstr3b", "gstr9", "itr", "tds_return", "aoc4", "mgt7"],
        "trigger_type": "on_sync_review",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "risk_report",
    },

    # Compliance Calendar
    {
        "key": "monthly_due_date_generator",
        "name": "Monthly Due Date Generator",
        "description": "Generate monthly due-date reminders by compliance type.",
        "category": "Compliance Calendar",
        "assigned_agent": "Compliance Calendar Agent",
        "task_types": ["due_dates"],
        "trigger_type": "scheduled",
        "risk_level": "low",
        "requires_human_review": False,
        "is_active": True,
        "output_type": "calendar_plan",
    },
    {
        "key": "overdue_task_escalation",
        "name": "Overdue Task Escalation",
        "description": "Escalation prompts for overdue compliance tasks.",
        "category": "Compliance Calendar",
        "assigned_agent": "Compliance Calendar Agent",
        "task_types": ["due_dates", "query"],
        "trigger_type": "scheduled",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "escalation_note",
    },

    # Reconciliation
    {
        "key": "books_vs_return_reconciliation",
        "name": "Books vs Return Reconciliation",
        "description": "Compare return-facing figures with books and note variances.",
        "category": "Reconciliation",
        "assigned_agent": "Reconciliation Agent",
        "task_types": ["gstr3b", "gstr9", "itr", "tds_return"],
        "trigger_type": "on_sync_review",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "reconciliation_note",
    },

    # Credential & Access
    {
        "key": "client_credential_checklist",
        "name": "Client Credential Checklist",
        "description": "Generate portal credential requirement checklist without storing secrets.",
        "category": "Credential & Access",
        "assigned_agent": "Credential & Access Agent",
        "task_types": ["document_checklist", "general_query"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "missing_portal_credentials_detector",
        "name": "Missing Portal Credentials Detector",
        "description": "Detect missing credential placeholders needed for filing readiness.",
        "category": "Credential & Access",
        "assigned_agent": "Credential & Access Agent",
        "task_types": ["document_checklist", "gstr3b", "itr", "aoc4", "pf_esi"],
        "trigger_type": "on_sync_review",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "risk_report",
    },
    {
        "key": "credential_expiry_alert",
        "name": "Credential Expiry Alert",
        "description": "Flag expiring access artifacts and suggest renewal actions.",
        "category": "Credential & Access",
        "assigned_agent": "Credential & Access Agent",
        "task_types": ["general_query", "document_checklist"],
        "trigger_type": "scheduled",
        "risk_level": "medium",
        "requires_human_review": False,
        "is_active": True,
        "output_type": "alert",
    },
    {
        "key": "portal_access_readiness_check",
        "name": "Portal Access Readiness Check",
        "description": "Assess whether access prerequisites are complete before portal actions.",
        "category": "Credential & Access",
        "assigned_agent": "Credential & Access Agent",
        "task_types": ["gstr3b", "itr", "aoc4", "pf_esi", "document_checklist"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "risk_report",
    },

    # Portal RPA
    {
        "key": "gst_login_readiness_check",
        "name": "GST Login Readiness Check",
        "description": "Pre-flight validation checklist for GST portal login prerequisites.",
        "category": "Portal RPA",
        "assigned_agent": "GST Portal RPA Agent",
        "task_types": ["gstr3b", "general_query"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "gst_2b_download_job",
        "name": "GST 2B Download Job",
        "description": "Track and prepare steps for GST 2B retrieval workflow.",
        "category": "Portal RPA",
        "assigned_agent": "GST Portal RPA Agent",
        "task_types": ["gstr3b"],
        "trigger_type": "scheduled",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "status_update",
    },
    {
        "key": "gst_return_status_check",
        "name": "GST Return Status Check",
        "description": "Monitor GST return filing status checkpoints for assigned tasks.",
        "category": "Portal RPA",
        "assigned_agent": "Portal Status Monitor Agent",
        "task_types": ["gstr3b"],
        "trigger_type": "scheduled",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "status_update",
    },
    {
        "key": "gst_challan_download_job",
        "name": "GST Challan Download Job",
        "description": "Prepare/download tracking flow for GST challan records.",
        "category": "Portal RPA",
        "assigned_agent": "GST Portal RPA Agent",
        "task_types": ["gstr3b"],
        "trigger_type": "on_sync_review",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "status_update",
    },
    {
        "key": "income_tax_login_readiness_check",
        "name": "Income Tax Login Readiness Check",
        "description": "Pre-flight validation checklist for Income Tax portal access.",
        "category": "Portal RPA",
        "assigned_agent": "Income Tax Portal RPA Agent",
        "task_types": ["itr", "general_query"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "ais_download_job",
        "name": "AIS Download Job",
        "description": "Track AIS retrieval workflow and readiness checkpoints.",
        "category": "Portal RPA",
        "assigned_agent": "Income Tax Portal RPA Agent",
        "task_types": ["itr"],
        "trigger_type": "scheduled",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "status_update",
    },
    {
        "key": "form_26as_download_job",
        "name": "Form 26AS Download Job",
        "description": "Track 26AS retrieval workflow and capture completion status.",
        "category": "Portal RPA",
        "assigned_agent": "Income Tax Portal RPA Agent",
        "task_types": ["itr"],
        "trigger_type": "scheduled",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "status_update",
    },
    {
        "key": "itr_status_check",
        "name": "ITR Status Check",
        "description": "Monitor ITR filing/processing status milestones.",
        "category": "Portal RPA",
        "assigned_agent": "Portal Status Monitor Agent",
        "task_types": ["itr"],
        "trigger_type": "scheduled",
        "risk_level": "medium",
        "requires_human_review": False,
        "is_active": True,
        "output_type": "status_update",
    },
    {
        "key": "mca_login_readiness_check",
        "name": "MCA Login Readiness Check",
        "description": "Pre-flight validation checklist for MCA portal access.",
        "category": "Portal RPA",
        "assigned_agent": "MCA Portal RPA Agent",
        "task_types": ["aoc4", "general_query"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "mca_master_data_fetch",
        "name": "MCA Master Data Fetch",
        "description": "Track company master data retrieval workflow from MCA.",
        "category": "Portal RPA",
        "assigned_agent": "MCA Portal RPA Agent",
        "task_types": ["aoc4"],
        "trigger_type": "on_sync_review",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "status_update",
    },
    {
        "key": "mca_form_status_check",
        "name": "MCA Form Status Check",
        "description": "Monitor MCA form progression and acknowledgment status.",
        "category": "Portal RPA",
        "assigned_agent": "Portal Status Monitor Agent",
        "task_types": ["aoc4"],
        "trigger_type": "scheduled",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "status_update",
    },
    {
        "key": "mca_challan_download_job",
        "name": "MCA Challan Download Job",
        "description": "Track MCA challan retrieval workflow and handoff status.",
        "category": "Portal RPA",
        "assigned_agent": "MCA Portal RPA Agent",
        "task_types": ["aoc4"],
        "trigger_type": "on_sync_review",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "status_update",
    },
    {
        "key": "traces_form16_download_job",
        "name": "TRACES Form 16 Download Job",
        "description": "Track TRACES Form 16 retrieval workflow and completion.",
        "category": "Portal RPA",
        "assigned_agent": "TRACES RPA Agent",
        "task_types": ["tax_audit", "general_query"],
        "trigger_type": "scheduled",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "status_update",
    },
    {
        "key": "pf_esi_challan_status_check",
        "name": "PF/ESI Challan Status Check",
        "description": "Monitor PF/ESI challan generation/payment status checkpoints.",
        "category": "Portal RPA",
        "assigned_agent": "PF/ESI Portal RPA Agent",
        "task_types": ["pf_esi"],
        "trigger_type": "scheduled",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "status_update",
    },
    {
        "key": "portal_error_explanation",
        "name": "Portal Error Explanation",
        "description": "Convert portal error codes/messages into operator-friendly resolution notes.",
        "category": "Portal RPA",
        "assigned_agent": "Error Resolution Agent",
        "task_types": ["general_query", "gstr3b", "itr", "aoc4", "pf_esi"],
        "trigger_type": "on_sync_review",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "risk_report",
    },

    # Company Incorporation
    {
        "key": "pvt_ltd_incorporation_checklist",
        "name": "Private Limited Incorporation Checklist",
        "description": "Checklist for Pvt Ltd incorporation prerequisites and milestones.",
        "category": "Company Incorporation",
        "assigned_agent": "Company Incorporation Agent",
        "task_types": ["document_checklist", "general_query"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "opc_incorporation_checklist",
        "name": "OPC Incorporation Checklist",
        "description": "Checklist for OPC incorporation document and approval readiness.",
        "category": "Company Incorporation",
        "assigned_agent": "Company Incorporation Agent",
        "task_types": ["document_checklist", "general_query"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "llp_incorporation_checklist",
        "name": "LLP Incorporation Checklist",
        "description": "Checklist for LLP incorporation and filing readiness.",
        "category": "Company Incorporation",
        "assigned_agent": "LLP Incorporation Agent",
        "task_types": ["document_checklist", "general_query"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "name_approval_checklist",
        "name": "Name Approval Checklist",
        "description": "Checklist for name reservation rules and supporting inputs.",
        "category": "Company Incorporation",
        "assigned_agent": "Company Incorporation Agent",
        "task_types": ["document_checklist", "general_query"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "spice_plus_document_checklist",
        "name": "SPICe+ Document Checklist",
        "description": "Document checklist for SPICe+ preparation and submission.",
        "category": "Company Incorporation",
        "assigned_agent": "Company Incorporation Agent",
        "task_types": ["document_checklist", "general_query"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "moa_aoa_drafting_checklist",
        "name": "MOA/AOA Drafting Checklist",
        "description": "Checklist for MOA/AOA drafting quality and review gates.",
        "category": "Company Incorporation",
        "assigned_agent": "Company Incorporation Agent",
        "task_types": ["document_checklist", "general_query"],
        "trigger_type": "on_sync_review",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "draft_working",
    },
    {
        "key": "post_incorporation_compliance_checklist",
        "name": "Post Incorporation Compliance Checklist",
        "description": "Checklist for immediate post-incorporation filings and registrations.",
        "category": "Company Incorporation",
        "assigned_agent": "Company Incorporation Agent",
        "task_types": ["document_checklist", "general_query"],
        "trigger_type": "scheduled",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },

    # Registrations
    {
        "key": "gst_registration_checklist",
        "name": "GST Registration Checklist",
        "description": "Checklist for GST registration document and workflow readiness.",
        "category": "Registrations",
        "assigned_agent": "GST Registration Agent",
        "task_types": ["document_checklist", "general_query"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "udyam_registration_checklist",
        "name": "Udyam Registration Checklist",
        "description": "Checklist for Udyam/MSME registration data and document readiness.",
        "category": "Registrations",
        "assigned_agent": "MSME / Udyam Agent",
        "task_types": ["document_checklist", "general_query"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "startup_india_checklist",
        "name": "Startup India Checklist",
        "description": "Checklist for Startup India registration readiness and validations.",
        "category": "Registrations",
        "assigned_agent": "Startup India Agent",
        "task_types": ["document_checklist", "general_query"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "shops_establishment_checklist",
        "name": "Shops & Establishment Checklist",
        "description": "Checklist for Shops & Establishment registration by state requirements.",
        "category": "Registrations",
        "assigned_agent": "Shops & Establishment Agent",
        "task_types": ["document_checklist", "general_query"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "pf_esi_registration_checklist",
        "name": "PF/ESI Registration Checklist",
        "description": "Checklist for PF/ESI registration prerequisites and supporting proofs.",
        "category": "Registrations",
        "assigned_agent": "Labour Registration Agent",
        "task_types": ["pf_esi", "document_checklist"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "professional_tax_registration_checklist",
        "name": "Professional Tax Registration Checklist",
        "description": "Checklist for professional tax registration and state compliance setup.",
        "category": "Registrations",
        "assigned_agent": "Labour Registration Agent",
        "task_types": ["pf_esi", "document_checklist"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "fema_fdi_compliance_checklist",
        "name": "FEMA/FDI Compliance Checklist",
        "description": "Checklist for FEMA/FDI registration and reporting prerequisites.",
        "category": "Registrations",
        "assigned_agent": "FEMA / FDI Agent",
        "task_types": ["document_checklist", "general_query"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "business_license_checklist",
        "name": "Business License Checklist",
        "description": "Checklist for local/business license requirement tracking.",
        "category": "Registrations",
        "assigned_agent": "Business License Agent",
        "task_types": ["document_checklist", "general_query"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },

    # Evidence Management
    {
        "key": "gst_acknowledgement_capture",
        "name": "GST Acknowledgement Capture",
        "description": "Capture and catalog GST filing acknowledgement artifacts.",
        "category": "Evidence Management",
        "assigned_agent": "Filing Evidence Agent",
        "task_types": ["gstr3b"],
        "trigger_type": "on_sync_review",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "evidence_pack",
    },
    {
        "key": "income_tax_acknowledgement_capture",
        "name": "Income Tax Acknowledgement Capture",
        "description": "Capture and catalog ITR filing acknowledgement artifacts.",
        "category": "Evidence Management",
        "assigned_agent": "Filing Evidence Agent",
        "task_types": ["itr"],
        "trigger_type": "on_sync_review",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "evidence_pack",
    },
    {
        "key": "mca_acknowledgement_capture",
        "name": "MCA Acknowledgement Capture",
        "description": "Capture and catalog MCA filing acknowledgement artifacts.",
        "category": "Evidence Management",
        "assigned_agent": "Filing Evidence Agent",
        "task_types": ["aoc4"],
        "trigger_type": "on_sync_review",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "evidence_pack",
    },
    {
        "key": "challan_receipt_capture",
        "name": "Challan Receipt Capture",
        "description": "Capture challan receipts and map them to related compliance tasks.",
        "category": "Evidence Management",
        "assigned_agent": "Filing Evidence Agent",
        "task_types": ["gstr3b", "itr", "aoc4", "pf_esi"],
        "trigger_type": "on_sync_review",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "evidence_pack",
    },
    {
        "key": "filing_evidence_pack_builder",
        "name": "Filing Evidence Pack Builder",
        "description": "Assemble filing evidence bundle manifest for reviewer verification.",
        "category": "Evidence Management",
        "assigned_agent": "Filing Evidence Agent",
        "task_types": ["gstr3b", "itr", "aoc4", "pf_esi", "tax_audit"],
        "trigger_type": "on_sync_review",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "evidence_pack",
    },

    # Accounting Connectors
    {
        "key": "tally_sync_readiness_check",
        "name": "Tally Sync Readiness Check",
        "description": "Validate Tally sync prerequisites and source-data readiness.",
        "category": "Accounting Connectors",
        "assigned_agent": "Accounting Sync Agent",
        "task_types": ["general_query", "tax_audit", "gstr3b"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "zoho_books_sync_readiness_check",
        "name": "Zoho Books Sync Readiness Check",
        "description": "Validate Zoho Books connector and data mapping readiness.",
        "category": "Accounting Connectors",
        "assigned_agent": "Accounting Sync Agent",
        "task_types": ["general_query", "tax_audit", "gstr3b"],
        "trigger_type": "on_task_send_to_ai",
        "risk_level": "medium",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "checklist",
    },
    {
        "key": "manual_upload_data_validation",
        "name": "Manual Upload Data Validation",
        "description": "Validate accounting data uploaded manually before downstream use.",
        "category": "Accounting Connectors",
        "assigned_agent": "Accounting Sync Agent",
        "task_types": ["tax_audit", "gstr3b", "itr"],
        "trigger_type": "on_sync_review",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "risk_report",
    },
    {
        "key": "accounting_data_normalization_check",
        "name": "Accounting Data Normalization Check",
        "description": "Check normalized chart/ledger mapping quality for automation use.",
        "category": "Accounting Connectors",
        "assigned_agent": "Accounting Sync Agent",
        "task_types": ["tax_audit", "gstr3b", "itr"],
        "trigger_type": "on_sync_review",
        "risk_level": "high",
        "requires_human_review": True,
        "is_active": True,
        "output_type": "risk_report",
    },
]


def _text(value) -> str:
    return str(value or "").strip()


def list_automations(category=None, agent=None, task_type=None, active_only=False, search=None):
    """Return filtered automation registry entries."""
    category = _text(category)
    agent = _text(agent)
    task_type = _text(task_type)
    search = _text(search).lower()

    results = []
    for automation in AUTOMATION_REGISTRY:
        if active_only and not automation.get("is_active"):
            continue

        if category and automation.get("category") != category:
            continue

        if agent and automation.get("assigned_agent") != agent:
            continue

        if task_type and task_type not in (automation.get("task_types") or []):
            continue

        if search:
            haystack = " ".join(
                [
                    _text(automation.get("key")),
                    _text(automation.get("name")),
                    _text(automation.get("description")),
                    _text(automation.get("category")),
                    _text(automation.get("assigned_agent")),
                    " ".join(automation.get("task_types") or []),
                ]
            ).lower()
            if search not in haystack:
                continue

        results.append(dict(automation))

    return results


def get_automation(key):
    """Return a single automation by key, or None."""
    key = _text(key)
    if not key:
        return None

    for automation in AUTOMATION_REGISTRY:
        if automation.get("key") == key:
            return dict(automation)
    return None


def get_automations_for_task_type(task_type):
    """Return active automations mapped to the provided task type."""
    task_type = _text(task_type)
    if not task_type:
        return []

    return [
        dict(automation)
        for automation in AUTOMATION_REGISTRY
        if automation.get("is_active") and task_type in (automation.get("task_types") or [])
    ]


def get_default_agent_for_task_type(task_type):
    """Return the most common active assigned agent for a task type."""
    automations = get_automations_for_task_type(task_type)
    if not automations:
        return None

    counts = Counter([a.get("assigned_agent") for a in automations if a.get("assigned_agent")])
    if not counts:
        return None

    return counts.most_common(1)[0][0]


def get_registry_summary():
    """
    Return aggregate metrics for registry dashboard cards and side summaries.

    Keys:
      total_automations
      active_automations
      category_counts
      agent_counts
      high_risk_count
      human_review_required_count
    """
    total = len(AUTOMATION_REGISTRY)
    active = sum(1 for a in AUTOMATION_REGISTRY if a.get("is_active"))
    high_risk = sum(1 for a in AUTOMATION_REGISTRY if _text(a.get("risk_level")).lower() == "high")
    human_review = sum(1 for a in AUTOMATION_REGISTRY if bool(a.get("requires_human_review")))

    category_counts = Counter([a.get("category") for a in AUTOMATION_REGISTRY if a.get("category")])
    agent_counts = Counter([a.get("assigned_agent") for a in AUTOMATION_REGISTRY if a.get("assigned_agent")])

    return {
        "total_automations": total,
        "active_automations": active,
        "category_counts": dict(category_counts),
        "agent_counts": dict(agent_counts),
        "high_risk_count": high_risk,
        "human_review_required_count": human_review,
    }
